# Generated by Django 4.0.3 on 2022-03-26 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='BlogPublishDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
