# Generated by Django 4.0.3 on 2022-04-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_blog_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='BlogImage',
            field=models.ImageField(blank=True, default='NULL', upload_to='images/post/%Y/%m/%d/'),
        ),
    ]
