# Generated by Django 4.0.3 on 2022-04-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Categories',
            field=models.ManyToManyField(to='Post.category'),
        ),
    ]
