# Generated by Django 4.0.3 on 2022-04-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_alter_blog_blogcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='BlogCategory',
            field=models.ForeignKey(null=True, on_delete=models.SET(4), to='Post.category'),
        ),
    ]
