# Generated by Django 4.0.3 on 2022-04-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_alter_blog_blogcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('TagID', models.AutoField(primary_key=True, serialize=False)),
                ('TagName', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='BlogTags',
            field=models.ManyToManyField(to='Post.tag'),
        ),
    ]
