# Generated by Django 4.0.3 on 2022-03-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('NewsID', models.AutoField(primary_key=True, serialize=False)),
                ('NewsTitle', models.CharField(default='No Title', max_length=50)),
                ('NewsBody', models.TextField()),
            ],
        ),
    ]
